apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: kube-system
  labels:
    application: kube-state-metrics
    version: v1.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-state-metrics
  template:
    metadata:
      labels:
        application: kube-state-metrics
        version: v1.1.0
    spec:
      containers:
      - image: registry.opensource.zalan.do/teapot/kube-state-metrics:v1.1.0
        name: kube-state-metrics
        ports:
        - containerPort: 8080
        command:
        - /kube-state-metrics
        - --port=8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 25Mi
