apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel
  namespace: kube-system
  labels:
    application: flannel
    version: v0.9.1
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      application: flannel
  template:
    metadata:
      labels:
        application: flannel
        version: v0.9.1
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: system
      containers:
      - name: kube-flannel
        image: registry.opensource.zalan.do/teapot/flannel:v0.9.1
        args:
        - --kube-subnet-mgr
        - --iface=$(POD_IP)
        - --ip-masq
        - --healthz-ip=127.0.0.1
        - --healthz-port=7978
        - --v=2
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 25m
            memory: 25Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: flannelcfg
          mountPath: /etc/kube-flannel
        - name: runflannel
          mountPath: /run/flannel
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      - operator: Exists
        key: CriticalAddonsOnly
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      volumes:
      - name: flannelcfg
        configMap:
          name: kube-flannel-cfg
      - name: runflannel
        hostPath:
          path: /run/flannel
