apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube2iam
  namespace: kube-system
  labels:
    application: kube2iam
    version: v0.7.0
spec:
  selector:
    matchLabels:
      application: kube2iam
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: kube2iam
        version: v0.7.0
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostNetwork: true
      containers:
      - image: registry.opensource.zalan.do/teapot/kube2iam:0.7.0
        name: kube2iam
        args:
        - --auto-discover-base-arn
        - --verbose
        ports:
        - containerPort: 8181
          hostPort: 8181
          name: http
        securityContext:
          privileged: true
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8181
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 25m
            memory: 25Mi
