# example: remove the app-ingress-controller deployment from kube-system
# pre_apply:
# - name: app-ingress-controller
#   namespace: kube-system
#   kind: deployment

pre_apply: # everything defined under here will be deleted before applying the manifests
- name: emergency-access-service
  namespace: kube-system
  kind: deployment
- name: emergency-access-service
  namespace: kube-system
  kind: service
- name: emergency-access-service
  namespace: kube-system
  kind: ingress
- name: emergency-access-service-secrets
  namespace: kube-system
  kind: secret
- name: cluster-autoscaler
  namespace: kube-system
  kind: deployment
- name: cluster-autoscaler-playground
  namespace: kube-system
  kind: configmap
- name: cluster-autoscaler-production
  namespace: kube-system
  kind: configmap
- name: cluster-autoscaler-test
  namespace: kube-system
  kind: configmap
post_apply: # everything defined under here will be deleted after applying the manifests
- name: kube-job-cleaner
  namespace: kube-system
  kind: cronjob

